// <auto-generated />
using System;
using L3T.Infrastructure.Helpers.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L3T.Infrastructure.Helpers.Migrations
{
    [DbContext(typeof(TicketDataWriteContext))]
    partial class TicketDataWriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("L3T.Infrastructure.Helpers.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("L3T.Infrastructure.Helpers.Models.Ticket.TicketEntry", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketId"), 1L, 1);

                    b.Property<string>("AssignEngineer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CauseOfDelay")
                        .HasColumnType("int");

                    b.Property<int>("CauseOfTermination")
                        .HasColumnType("int");

                    b.Property<int>("CloseCategory")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplainCategory")
                        .HasColumnType("int");

                    b.Property<string>("ComplainReceiveby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplainSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complains")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompleteBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysExtension")
                        .HasColumnType("int");

                    b.Property<string>("DeviceCollectionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecuteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FaultOccured")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ForwardDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenerateTicketSupportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBussinessHour")
                        .HasColumnType("bit");

                    b.Property<string>("IsUrgentSupport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastComments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LedStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MqID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONUBW")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONULASER")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONUPORT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONUSTATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PendingReasonID")
                        .HasColumnType("int");

                    b.Property<string>("PendingTeamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REBOOT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceiveDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefeNoActivity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleStatus")
                        .HasColumnType("int");

                    b.Property<string>("SourceMobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceOfInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskCategory")
                        .HasColumnType("int");

                    b.Property<int>("TaskNature")
                        .HasColumnType("int");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TerminateExcuteDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraceLess_Schedule")
                        .HasColumnType("int");

                    b.Property<string>("USERMAC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brCliCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("brSlNo")
                        .HasColumnType("int");

                    b.Property<string>("vicidial_call_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketId");

                    b.ToTable("TicketEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
